// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareInvest.Data;

#nullable disable

namespace ShareInvest.Data.Migrations
{
    [DbContext(typeof(ForestTripContext))]
    [Migration("20241020100839_CreatePolicy")]
    partial class CreatePolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ShareInvest.Models.Cabin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Name");

                    b.ToTable("Cabin", (string)null);
                });

            modelBuilder.Entity("ShareInvest.Models.ForestRetreat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForestRetreat", (string)null);
                });

            modelBuilder.Entity("ShareInvest.Models.Policy", b =>
                {
                    b.Property<string>("ResortId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cabin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Campsite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reservation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Wait")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResortId");

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("ShareInvest.Models.Reservation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForestRetreat")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StartDate", "ForestRetreat", "CabinName");

                    b.ToTable("Reservations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
